apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: pilot-potentialpark-com-tls
spec:
  secretName: pilot-potentialpark-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: pilot.potentialpark.com
  dnsNames:
    - pilot.potentialpark.com
  acme:
    config:
      - http01:
          ingress: ingress-service
        domains:
          - pilot.potentialpark.com
